### ISSUE TITLE
What is the point of the Void Herrcher?

### ISSUE THREAD

**Issue by SomeRandomPetey** [ExtraMeteorP/Extra-Botany#49]
This isn't really an issue, but more of a question. What is the whole point of the Void Herrscher fight? The boss drops the exact same things as the Gaia Guardian III, and it is so much more harder. Is it planned to drop other things?

**Comment by ExtraMeteorP** [comment]
For those people who want challenges, because many people think Gaia 3 is not powerful enough while many others are complaining that it’s quite impossible to beat it. I don’t want it to become a burden, so they drop exactly the same, except that two advancements and two cosmetic baubles are gated behind. Maybe more symbolic cosmetic baubles will be added.

**Comment by idolvlad** [comment]
how to kill herrscher of the void She has 1 HP left and doesn’t want to die! There is no information anywhere! I could not do this with the help of Escalibur. There is no information anywhere!
