### ISSUE TITLE
Server loop Gaia III

### ISSUE THREAD

**Issue by bigenergy** [ExtraMeteorP/Extra-Botany#63]
https://pastebin.com/7m21H4S5

**Comment by TheDirectorX** [comment]
**Did you build an arena out of water for Gaia? Because Gaia begins to quickly destroy blocks of water, lags can occur because of this.** https://github.com/ExtraMeteorP/Extra-Botany/issues/58#issue-455811411

_P.S. Всегда описывайте вашу проблему хоть как-то, когда это начало происходит и при каких условиях. Нужно больше данных, если вы хотите, чтобы вашу проблему решили._

**Comment by bigenergy** [comment]
arena without water
but under a layer of earth

**Comment by ExtraMeteorP** [comment]
thats it. It clears a wide range of water, so people should not build arena near or above water

**Comment by bigenergy** [comment]
> thats it. It clears a wide range of water, so people should not build arena near or above water

And how should they know about it?

**Comment by TheDirectorX** [comment]
**Gaia III’s blocks destruction radius is 20x20x20. From the beacon 10 blocks from all sides.**
![2019-07-02_22 52 55](https://user-images.githubusercontent.com/43481085/60535708-2f521900-9d1e-11e9-9a49-dae8daa29243.png)

- [ ] **Probable solution for the developer:** make the destruction of liquids like a Gaia from Botania _(3x3x3)_,![2019-07-02_22 58 27](https://user-images.githubusercontent.com/43481085/60536153-17c76000-9d1f-11e9-9540-8735a50dc64f.png)but at the same time leave the radius of destruction of all other blocks.

**Comment by ExtraMeteorP** [comment]
no longer clear water in r55
